plugins {
    id 'application'
    id 'java'
}

group 'com.poolapp'
version '1.0-SNAPSHOT'

layout.buildDirectory.set(layout.projectDirectory.dir("gradle-build"))

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.40.1.0'
    implementation 'org.apache.pdfbox:pdfbox:3.0.1'
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
}

application {
    mainClass.set('com.poolapp.Main')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
